name: Unzip Uploaded Files

on:
  push:
    paths:
      - '*.zip'

jobs:
  unzip:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install unzip
      run: sudo apt-get install -y unzip

    - name: Unzip file
      run: |
        for file in *.zip; do
          unzip -o "$file" -d "${file%.*}"
        done
